spring:
    application:
        name: gestao-reservas
    datasource:
        url: jdbc:mysql://localhost:3306/gestao_reservas
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false